### ISSUE TITLE
Improve Repo Documentation

### ISSUE THREAD

**Issue by snadi** [ualberta-smr/SOCommentEditsMapping#25]
- Readme:
  - [ ] need to update the repo tag and link in ReadMe so it includes the updates to the readme (keep as last step)
  - [x]  Seems like an incomplete sentence "A guide to install SQLite to your"
  - [x]  In the running steps, shouldn't the first step before running talk about the Config.ini file and what you might need to set there>
  - [x]  In the eval option, it says it will compare against ground_truth.csv but in the data below, you say this ground truth is not what was used in the paper. Also, during this comparison, does it run the matching only on the comments and edits of answers in the ground truth? In other words, how do I tell the program to run only on the data in the ground truth in the previous run to produce the results.csv to compare to?
  - [x]  Please paraphrase the Pack option. It's a bit confusing.. it says "tells the program to take a csv ..." but it doesnt' say take it and do what with it. First, explain what it does then explain its required input and expected output
  - [x]  I don't remember now: in the paper, do we mention that we use the False option for user? I.e., that the comment and edit author must be different? 

- Data directory wiki:
  - [x] I don't understand what example_results.json means. It says a single answer but the name of the file is example_results? Either the name or description needs to be updated to be more intuitive
  - [x]   general_precision.json: explain what these are. How were they sampled? How many per tag? For  What does it mean "used for general precision"? Be a bit more specific. For example, "that the two authors manually validated to determine the general precision of our matching algorithm"
  - [x]   ground_truth.csv: not sure what that is if it is not the same as in the paper? How was it formed and what is it used for then? Please be detailed and explain things. Neither of us will remember these things later and if we or others want to reuse this work, things should be clear.

- pull_requests.csv : why time of submission? Isn't this the final updated info>

- SQL Scripts and Importing Wiki:
  - [x] How can I create tables to store the data in the csvs? Do you already have scripts for that? Should I just use the schemas you provide? Do I need to do anything extra? Can you provide a sequence of commands to use? What do i do with .mode csv?

- Results Wiki:

  - [x] Link for importing section is missing
  - [x] So what's the schema for Answer Ids to import it into DB? Is there an automated way to do this?
  - [x] Additionally, the PostBlockvERSION.csv ... is provided in case ... => so how do I do that? how can I create it without downloading the whole dump? Are instructions on ReadMe?
  - [x] How do I import the results csv into the DB>
  - [x] Point 4: maybe include the concrete sections of the paper
  - [x] For point 4: can you point to the script that is used to calculate let's say stats? Like this is the concrete result. If I want to reproduce it or replicate it, what would I do?
  - [x] For the example json part, can you just add 1-2 intro sentences about what the point of these json files are? Like why did we convert to json and what would be expected.

- Json Packaging Page

  - [x] At the top of the page, maybe add something to describe what the point of this packaging step is. You can say something while this is not part of the paper, we wanted to create a more processable format for the identified pairs. Thus, we have an option to produce json output bla bla .. 
  - [x]   * when you say "single result", do you mean an identified comment-edit pair? Maybe be a bit more precise in the terminology

**Comment by Hk-tang** [comment]
In the paper, we do not mention we take into account the commenter and editor being different users.

**Comment by snadi** [comment]
We need to be explicit about any assumptions we make or factors we take into account. Can you please update it?

**Comment by Hk-tang** [comment]
Do you mean to add that information into the paper?

**Comment by snadi** [comment]
Yes, add the info to the paper.

**Comment by Hk-tang** [comment]
I added the changes to the paper in this [commit](https://github.com/ualberta-smr/paper-socomments/commit/73fa2c45b5fbee66f1703a7f7c621e7f76da8413). I also addressed the other points here (except for the first point). Let me know if there are still changes to be made.

**Comment by snadi** [comment]
I still see the incomplete sentence in the readme: "A guide to install SQLite to your"

**Comment by Hk-tang** [comment]
Sorry, I forgot to push

**Comment by snadi** [comment]
> * ground_truth.csv: not sure what that is if it is not the same as in the paper? How was it formed and what is it used for then? Please be detailed and explain things. Neither of us will remember these things later and if we or others want to reuse this work, things should be clear.

So now it reads "This CSV file is not the exact ground truth file we used in the paper, but it is the as the ground truth in the paper. " -- the sentence is grammatically strange "the as". It;s still not clear. So (1) where is the exact ground truth used in the paper and (2) maybe simply to just say this is the same ground truth in a shortened format to be used by the program for comparison (if this is what you mean). It's just not clear to me why there is less info here. 

Otherwise, looks good to me.

One note here is that we still need to create a release for this repo in order to be able to create the zenodo archive. But one thing I'm not sure of: I don't think the wiki pages are part of the release. As such, I'm wondering if it is better to take all the important wiki pages, turn them into md files in the repo under a `doc` folder and change the links in the readme (and any of the wiki pages to reflect that), such that they are part of the release? Maybe test if there's a way to easily package the wiki pages into the release first?

**Comment by snadi** [comment]
Oh and for the paper changes, I put some comments directly there.

**Comment by Hk-tang** [comment]
It seems, we can not add wiki pages to a release. I will add them as md files and modify the links, but I will leave the wiki pages up. I also modified the paper again, and changed the ground_truth.csv description.
